// FLOW — The Future Land of Wonder
// Single source of truth for the sticker line-up.
// Drop a real PNG at images/<slug>.png and it replaces the placeholder automatically.
window.FLOW_PRODUCTS = [
  {
    slug: 'flow-pirates',
    title: 'Pirates of the FLOW-ribbean',
    blurb: 'Skull, cutlasses and a galleon under a blood-orange sunset. Yo-ho.',
    parody: 'Pirates of the Caribbean',
    price: 4.99,
    accent: '#c9a227',
    tags: ['movies', 'classic'],
  },
  {
    slug: 'flow-flowfather',
    title: 'The FLOWfather',
    blurb: 'Gold-foil mob royalty. An offer you can’t outflow.',
    parody: 'The Godfather',
    price: 4.99,
    accent: '#d4af37',
    tags: ['movies', 'classic'],
  },
  {
    slug: 'flow-jurassic',
    title: 'FLOW Park',
    blurb: 'Apex-predator red. The future land where the dinos roam.',
    parody: 'Jurassic Park',
    price: 4.99,
    accent: '#d32f2f',
    tags: ['movies'],
  },
  {
    slug: 'flow-wars',
    title: 'FLOW Wars',
    blurb: 'A galaxy far, far in the flow. May the flow be with you.',
    parody: 'Star Wars',
    price: 4.99,
    accent: '#f4c20d',
    tags: ['movies'],
  },
  {
    slug: 'flow-fresh',
    title: 'FLOW Fresh',
    blurb: 'Crown-topped bubble graffiti dripping in sunset gradients.',
    parody: 'Street / graffiti',
    price: 3.99,
    accent: '#ff5db1',
    tags: ['street'],
  },
  {
    slug: 'flow-zelda',
    title: 'Legend of FLOW',
    blurb: 'Triforce crest on the Hylian shield. It’s dangerous to go without flow.',
    parody: 'The Legend of Zelda',
    price: 4.99,
    accent: '#2e7d32',
    tags: ['games'],
  },
  {
    slug: 'flow-tv',
    title: 'FLOW TV',
    blurb: 'Neon green-pink drip with a glitchy retro set. Static never looked so clean.',
    parody: 'Street / retro',
    price: 3.99,
    accent: '#23e08a',
    tags: ['street'],
  },
  {
    slug: 'flow-street',
    title: 'FLOW Street',
    blurb: 'Wildstyle throw-up sprayed straight onto the concrete.',
    parody: 'Street / graffiti',
    price: 3.99,
    accent: '#f4b400',
    tags: ['street'],
  },
  {
    slug: 'flow-grey',
    title: 'FLOW the Grey',
    blurb: 'Chrome wildstyle with a wizard standing watch. You shall not outflow.',
    parody: 'The Lord of the Rings',
    price: 4.99,
    accent: '#9b6dff',
    tags: ['movies', 'street'],
  },
];
